require 'pp'

lane :hello do
  if sh('ls -l; ls -a') { |s| s.success? }
    UI.success "1" * 10
  else
    UI.error "2" * 10
  end
end

lane :test do
  # git = 'git@git.in.xxx.com:xxx/xxx.git'

  # ok
  # ret = git_clone(git: git, path: '/Users/xiongzenghui/Desktop/adsasd/haha')
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   branch: 'master'
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   branch: 'master',
  #   tag: '6.19.0' #=> error
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   tag: '6.19.0'
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   branch: 'master',
  #   depth: 1,
  #   single_branch: true
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   commit: '4f4ba',
  #   single_branch: true
  #   # depth: 1, #=> error
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   branch: 'master',
  #   commit: '3bb26661',
  #   # tag: '1.0.0', # => error
  # )
  # pp ret

  # ok
  # ret = git_clone(
  #   git: git,
  #   path: '/Users/xiongzenghui/Desktop/adsasd/haha',
  #   branch: 'master',
  #   update: true
  # )
  # pp ret
end
